stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/test.csv
    - data/train.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/train.csv
      - data/test.csv
    outs:
      - models/random_forest.joblib
      - metrics/metrics.csv

plots:
  - max_depth vs accuracy:
      template: simple
      x: "max_depth"
      y:
        metrics.csv: accuracy
  - max_depth vs f1_score:
      template: simple
      x: "max_depth"
      y:
        metrics.csv: f1_score